### PR TITLE
code to create PascalsTriangle

### PR DESCRIPTION
**Pull request by anujakatiyar**
solved issue #224

### CODE REVIEW

**Comment by akkupy** [comment]
Use correct file extension

**Comment by Dhruval7878** [comment]
Can i provide command for this in java ?

**Comment by akkupy** [comment]
Yes you can

**Comment by Shreshth-Srivastava** [comment]
May I provide a different code for this in python ?

**Comment by akkupy** [comment]
@Shreshth-Srivastava Yes Create a new issue.

**Pull request closed without merging**
